name: Database Migration for PostgreSQL

on: 
  push:
    branches:
      - main
    paths:
        - database_migrations/postgresql_local/**

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Install Flyway
        run: sudo apt-get install -y flyway
      
      # DB_PASSWORD: ${{ secrets.DB2_PASSWORD }}
      - name: Run Flyway Migrations for postgresql_local_db
        env:
          DB_PASSWORD: password
        run: flyway -url=jdbc:postgresql://localhost:5432/db_local_test -locations=filesystem:./database_migrations/postgresql_local migrate
