name: Database Migration for PostgreSQL

on: 
  push:
    branches:
      - main
      - flyway*
    paths:
        - database_migrations/postgresql_local/**
        - .github/workflows/ci_postgresql_local.yml

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup environment variables
        run: |
          echo "FLYWAY_VERSION=10.15.2" >> $GITHUB_ENV
          
      - name: Install Flyway
        run: |
          curl -L "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${{ env.FLYWAY_VERSION }}/flyway-commandline-${{ env.FLYWAY_VERSION }}-linux-x64.tar.gz" | tar xvz
          sudo ln -s `pwd`/flyway-${{ env.FLYWAY_VERSION }}/flyway /usr/local/bin/flyway
      
      # DB_PASSWORD: ${{ secrets.DB2_PASSWORD }}
      - name: Run Flyway Migrations for postgresql_local_db
        env:
          DB_USER: melih
          DB_PASSWORD: password
        run: flyway -url=jdbc:postgresql://localhost:5432/db_local_test -user=${DB_USER} -password=${DB_PASSWORD} -locations=filesystem:./database_migrations/postgresql_local migrate
